### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ar-mokhtari**
For Linux, I can run a program with kahroba with ./kahroba main.kahroba

### CODE REVIEW

**Comment by amirmalekian** [comment]
I tested and the `./kahroba: command not found` error returns

**Comment by ar-mokhtari** [comment]
> I tested and the `./kahroba: command not found` error returns

Please test by executing the file (https://github.com/kahroba-lang/kahroba/releases/download/0.1/kahroba) in your root.
image

**Comment by amirmalekian** [comment]
kahroba

**Comment by ar-mokhtari** [comment]
> kahroba

https://github.com/kahroba-lang/kahroba/issues/5#issuecomment-1231393357

**Comment by amirmalekian** [comment]
Yes, it was done.
Thanks.

**Pull request merged**
